Repository BostonUniversitySeniorDesign/brain-4ce, pull requests merged in 2023-05, with the labels that each got.

#18 Add 3D Virtual Environment
  Virtual Environment/generate.py
  Virtual Environment/main.py
  Virtual Environment/models/brain.bam
  Virtual Environment/models/plane.bam
  Virtual Environment/models/star.bam
  Virtual Environment/models/star_texture.jpg
  Virtual Environment/models/water.png
  Virtual Environment/my-objects/barrier.egg
  Virtual Environment/my-objects/plane.egg
  Virtual Environment/my-objects/sphere.egg
  Virtual Environment/myConfig.prc
Labels: enhancement, needs review

#27 add software readme
  Documents/2d_game.png
  Documents/venv.png
  Virtual Environment/README_SOFTWARE.md
Labels: documentation, needs review

#19 Add Data Collection GUI
  Data Collection/find_cyton.py
  Data Collection/main.py
  Data Collection/taskwindow.py
  GUI/main.py
  GUI/savewindow.py
  GUI/taskwindow.py
Labels: enhancement, needs review

#23 Merge Bshortall fork into main
  Model/DataLoader.py
  Model/FBCNetwork.py
  Model/Filter.py
  Model/Train.py
  Model/Trainer.py
  Model/predict.py
  Model/requirements.txt
  hardware/mechanical/Case_Drawings.dwg
Labels: needs review
