Repository BostonUniversitySeniorDesign/brain-4ce, pull requests merged in 2023-04, with the labels that each got.

#10 Add Board Streaming Prototype
  .gitignore
  boardStreamer/.vscode/launch.json
  boardStreamer/__main__.py
  boardStreamer/find_cyton.py
  boardStreamer/requirements.txt
  firmware/main/main.ino
Labels: enhancement, Hardware, WIP

#13 Adding bootloader hex file and bootloader instructions to README
  firmware/README.md
  firmware/UDB32-MX2-DIP.hex
Labels: needs review

#12 Add PCA, CAD drawings, previous commits, and fake ML
  .gitignore
  Physionet Dataloader/Channel Placement.JPG
  Physionet Dataloader/Channels_Ranked.csv
  Physionet Dataloader/PCA.py
  Physionet Dataloader/Physionet_Dataloader.py
  hardware/mechanical/CaseCover_V2.stl
  hardware/mechanical/Case_Drawings.dwg
  hardware/mechanical/Case_V3.stl
  hardware/mechanical/Clip_wElectrode.stl
  hardware/mechanical/Cover_V3.stl
  hardware/mechanical/CytonWired_CaseV1.stl
  hardware/mechanical/CytonWired_CaseV2.stl
  hardware/mechanical/Frame.stl
Labels: needs review

#17 2d game
  2D Game/main.py
  2D Game/requirements.txt
Labels: enhancement, needs review

#24 Adding the Engineering Addendum to our repository for use by future teams
  .gitignore
  Documents/brain_4ce_logo.png
  Documents/team_photo.png
  README.md
  Virtual Environment/README_SOFTWARE.md
  hardware/README_HARDWARE.md
Labels: documentation, needs review
